---

spring:
  profiles: default
server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    
 
---
# host file edited mapping discovery-1 and discovery-2. otherwise client services are not registering
spring:
  profiles: server-1
  application:
    name: gateway-service
server:
  port: 8085
eureka:
  instance:
    hostname: zuul-1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-2:8762/eureka/
 
---
spring:
  profiles: server-2
  application:
    name: gateway-service
server:
  port: 8086
eureka:
  instance:
    hostname: zuul-2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-1:8761/eureka/